[package]
name = "day10"
version = "0.1.0"
authors = ["Aron Hansen Berggren <aronber@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
